services:
  frontend:
    build:
      context: .
      dockerfile: apps/neodraw-frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_HTTP_BACKEND=http://backend:3008
      - NEXT_PUBLIC_WS_URL=ws://ws:8080
    depends_on:
      - backend
      - ws

  backend:
    build:
      context: .
      dockerfile: apps/http-backend/Dockerfile
    ports:
      - "3008:3008"
    environment:
      - PORT=3008
      - DATABASE_URL=${DATABASE_URL}  

  ws:
    build:
      context: .
      dockerfile: apps/ws-backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}